#!/bin/sh -e
#
#    dotdee-inotify-handler - handle dotdee's inotify events
#    Copyright (C) 2011 Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="/etc/dotdee"

set -x

case "${1}" in
	# Only monitor the files in the dotdee-managed .d dirs
	${DIR}/*.d/[0-9]*|${DIR}/*.d/.comment)
		FILE=$(echo "${1}" | sed -e "s:^${DIR}::" -e "s:\.d/[0-9\.]\+.*$::")
		# Try to update the dotdee managed configuration
		exec dotdee --update "${FILE}"
	;;
	*)
		exit 0
	;;
esac
